### ISSUE TITLE
IndexError: list index out of range after firmware update

### ISSUE THREAD

**Issue by icolomer** [wijnandtop/home_assistant_gardena#4]
I was using the gardena smart component of rcastberg until a firmware update of my Sileno R130Li that seems that spoiled my setup.

I tried to deploy your component, but I have some errors like this on the logs:
***
2019-02-19 20:24:02 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 240, in async_update_ha_state
    device_attr = self.device_state_attributes
  File "/config/custom_components/vacuum/gardena.py", line 75, in device_state_attributes
    return self.robot.get_info()
  File "/config/deps/lib/python3.6/site-packages/wt/pygardena/mower.py", line 49, in get_info
    device_info['timestamp_next_start'] = self.get_timestamp_next_start()
  File "/config/deps/lib/python3.6/site-packages/wt/pygardena/mower.py", line 30, in get_timestamp_next_start
    return self.get_value_of_property('robotic_mower', 'timestamp_next_start')
  File "/config/deps/lib/python3.6/site-packages/wt/pygardena/device.py", line 18, in get_value_of_property
    return list(ability.execute('$.properties[@.name is '+property+']'))[0]['value']
IndexError: list index out of range
***
I guess that is a change of the cloud service, but I can not discard that is a deploy issue. Could you confirm that?

The firmware seems to be: 5825861-12A_P15G-SwPkg_19-2.9

**Comment by wijnandtop** [comment]
Haven’t tried it yet. My gardena equipment is currently boxed since I will move to a different location soon (so my mower has more lawn to mow).

Hopefully someone else can take a look else I will dive into this issue as soon as my mower is connected.

**Comment by wijnandtop** [comment]
I did some changes, which I couldn't test myself, since my equipment isn't available. Can you check if this solved your issue?

**Comment by icolomer** [comment]
Yes, is working perfectly now. Seems to be related to the update on the cloud service. 

Great job, thank you very much
