### ISSUE TITLE
Problem after Firmware Upgrade of Gardena Smart System

### ISSUE THREAD

**Issue by steveknoefler** [wijnandtop/home_assistant_gardena#7]
Hi,
do you know this problem? I think it came on after firmware upgrade to HomeKit update.

Error during setup of component gardena
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hass/.homeassistant/custom_components/gardena/__init__.py", line 39, in setup
    hass.data[GARDENA_LOGIN] = GardenaHub(hass, config[DOMAIN], GardenaSmartAccount)
  File "/home/hass/.homeassistant/custom_components/gardena/__init__.py", line 59, in __init__
    self.my_gardena = gardena(domain_config[CONF_USERNAME], domain_config[CONF_PASSWORD])
  File "/home/hass/.homeassistant/deps/lib/python3.5/site-packages/wt/pygardena/account.py", line 14, in __init__
    self.update_authtokens()
  File "/home/hass/.homeassistant/deps/lib/python3.5/site-packages/wt/pygardena/account.py", line 42, in update_authtokens
    self.AuthToken = response_data['sessions']['token']
KeyError: 'sessions'

thanks

**Comment by wijnandtop** [comment]
Haven’t tried it yet. My gardena equipment is currently boxed since I will move to a different location soon (so my mower has more lawn to mow).

Hopefully someone else can take a look else I will dive into this issue as soon as my mower is connected.

**Comment by tameike000** [comment]
+1 
Same problem here

**Comment by wijnandtop** [comment]
I did some changes, which I couldn't test myself, since my equipment isn't available. Can you check if this solved your issue?

**Comment by steveknoefler** [comment]
yes it´s working :)

thanks

**Comment by tameike000** [comment]
Can confirm, it works again! Sweet!

Thanks for the quick fix.
